### ISSUE TITLE
using any other name for S3 bucket than default name causes failure of stack creation.

### ISSUE THREAD

**Issue by plynch-indatasense** [aws-quickstart/quickstart-compliance-irap-protected#3]

**Comment by andrew-glenn** [comment]
@plynch-indatasense We leverage nested templates and pull assets from outside of CloudFormation. The `QSS3BucketName` parameter is where the assets load from. If you're looking to fork/host yourself, your S3 bucket should be populated with the contents of this repo. 

What's your intended use-case. I'm happy to help

**Comment by plynch-indatasense** [comment]
Andrew,
Make sense it initially looks to me that you could enter your own bucket
name for objects that would be created as part of cloudformation, not to
pull it from a central bucket.  My misundersatanding

**Comment by andrew-glenn** [comment]
No worries! Closing this out.
